apiVersion: v1
kind: Pod
metadata:
  name: fluent-sidecar-crd
  labels:
    app: fluent-sidecar-crd
spec:
  containers:
    - name: fluent-sidecar-crd
      image: fsc
      imagePullPolicy: IfNotPresent
  restartPolicy: Always